### ISSUE TITLE
Apply coupon code button on checkout page

### ISSUE THREAD

**Issue by imfaisalkh** [imfaisalkh/capstone-issue-tracker#10]
Green button is not displaying well to apply a new coupon code

http://prntscr.com/m3zvl0

`Posting on behalf of customer`

**Comment by imfaisalkh** [comment]
Should be fixed in next update.

**Comment by freudknows** [comment]
Issue still not fixed: http://prntscr.com/majrey

**Comment by freudknows** [comment]
Would you be able to post a screenshot of your coupon button, please?

**Comment by imfaisalkh** [comment]
@freudknows checkout page can be seen live here at this link: https://demo.wpscouts.net/capstone/checkout/?add-to-cart=417 and it looks like following:

![image](https://user-images.githubusercontent.com/10553273/52805658-df452380-30a8-11e9-9522-0e13e918287b.png)

**Comment by imfaisalkh** [comment]
Unable to reproduce.
