### ISSUE TITLE
Sign in page not working if Recaptcha field is enabled

### ISSUE THREAD

**Issue by imfaisalkh** [imfaisalkh/capstone-issue-tracker#14]
The sign in page is not working when the Recaptcha field (pro version) has been enabled. 

`Posting on behalf of customer`

**Comment by imfaisalkh** [comment]
I can confirm, the issue occurs when you use "invisible captcha" field, I'm not really sure what really is causing the issue, will look into it in more depth.

**Comment by freudknows** [comment]
It seems that the invisible captcha is not supported (yet) by the plugin developers of Profile Builder. 

Reply from developer: 
http://prntscr.com/m7vrzi

**Comment by imfaisalkh** [comment]
Thanks for reaching out to plugin developer. Since, it's a plugin related issue, I'm closing this issue.
