### ISSUE TITLE
Claim Listing plugin

### ISSUE THREAD

**Issue by imfaisalkh** [imfaisalkh/capstone-issue-tracker#22]
Would it be possible to make an integration with the Claim Listing Plugin? I think it's a great addition to the theme to show which jobs and companies are actually verified by the company owner. 

https://astoundify.com/products/wp-job-manager-claim-listing/

`Posting on behalf of customer`

**Comment by imfaisalkh** [comment]
Can you please explain this this a bit? Isn't it supposed to be the original company posting the jobs in first place? Why would any third-party post the jobs with some other company's name?

**Comment by freudknows** [comment]
Hi Faisal, I think this request only apply in my case. If none of your other customers will request the integration with this plugin, you can leave it from my part. Feel free to close this feature request.

**Comment by imfaisalkh** [comment]
I've usually seen this feature on city directory theme, I'm not aware of any use-case for job directory, if there is enough demand for it, I'll consider this feature but for now I'm closing it.
