### ISSUE TITLE
WP Job Manager Packages (Myles)

### ISSUE THREAD

**Issue by imfaisalkh** [imfaisalkh/capstone-issue-tracker#23]
Please include this plugin integration. This plugin is able to take WP Job Manager to the next level. Please check this link for more information: https://plugins.smyl.es/wp-job-manager-packages/ 

This plugin does not necessarily requires custom development for the theme, it's more a backend plugin without frontend info. 

`Posting on behalf of customer`

**Comment by imfaisalkh** [comment]
I'll take a look at this plugin in more detail, but if the plugin does not offers any functionality different from "WC Paid Listing" I might not add it to the list. I want to keep theme lean, this makes theme maintenance easier.

However, if it is backend-only plugin, this would not be an issue.

**Comment by freudknows** [comment]
This issue can be closed as it doesn't require any modification on the theme (frontend)? 

@imfaisalkh

**Comment by imfaisalkh** [comment]
I'll test the plugin with the theme, If it is working as expected I'll mark it as compatible and will close this issue.

**Comment by imfaisalkh** [comment]
Plugin integration added in theme v1.5
