### ISSUE TITLE
FacetWP Integration

### ISSUE THREAD

**Issue by imfaisalkh** [imfaisalkh/capstone-issue-tracker#24]
FacetWP allows advance filtering system for your listings: https://facetwp.com/

**Comment by freudknows** [comment]
More info how to combine with WP Job Manager:
https://facetwp.com/using-facetwp-with-wp-job-manager/

**Comment by freudknows** [comment]
What exactly will be possible with this plugin? Does it work with the fields editor of Myles? So you can decide which custom fields to show/hide of the search page? This would be very welcome!

**Comment by imfaisalkh** [comment]
This plugin should work with myles custom field editor (i see no reason why not). For example, if you create a custom field "Genre" with custom fields plugin, you should be able to create a filter (dropdown, checkbox etc) on left hand side, with facet-wp to display results ONLY from the genre(s) selected by the user while searching.

**Comment by CharlieW95** [comment]
Will this hook up with the location and the user can select a certain mileage distance for jobs within e.g. 5 miles, 10 miles 50 miles etc?

**Comment by imfaisalkh** [comment]
Yes, that would be possible using proximity facet: https://facetwp.com/documentation/proximity/

> Will this hook up with the location inputted and the user can select a certain mileage distance for jobs within e.g. 5 miles, 10 miles 50 miles etc?

**Comment by lisago82** [comment]
hello, I'd like to know when would it be ready

**Comment by imfaisalkh** [comment]
Plugin integration added in theme v1.7.0.
