### ISSUE TITLE
Ability to display custom fields on job details page

### ISSUE THREAD

**Issue by freudknows** [imfaisalkh/capstone-issue-tracker#27]
It would be great to display the output value of the Myles custom fields plugin for WP Job Manager on job detail pages. My suggestion would be to create an extra area where to display the custom fields with an icon, custom field label and field value. 

My suggestion would be to add them to this overview area:
http://prntscr.com/m6w67t

Thanks!

**Comment by imfaisalkh** [comment]
Yes, this plugin's integration is planned. Duplicate #3

**Comment by imfaisalkh** [comment]
Plugin integration added in theme v1.5
