### ISSUE TITLE
Extended WooCommerce functionality requested

### ISSUE THREAD

**Issue by freudknows** [imfaisalkh/capstone-issue-tracker#29]
We've had a small conversation about this before. You told me that only the checkout page will be included in the styling of this theme. I completely agree with the idea to strip every unessacary page of WC which is not being used. 

However, if you choose a package and add a different product later to the basket, it will give you different errors which does not have any styling. 

My request would be to include _all_ error styling of WC (also on basket and checkout page). 

Thanks.

**Comment by freudknows** [comment]
Issue #1: http://prntscr.com/majymh No visual support to create an account on checkout page.

**Comment by freudknows** [comment]
Issue #2: http://prntscr.com/mak07w placeholder 'password'?

**Comment by freudknows** [comment]
Issue #3: http://prntscr.com/mak1c7 placeholder to choose bank is missing (it's different compared to the other placeholders)

**Comment by freudknows** [comment]
Issue #4: http://prntscr.com/mak3fh validation checks does not really fit visually in the theme. The colors green, red, pink and purple combined?

**Comment by freudknows** [comment]
Issue #5: internal server error on checkout page: http://prntscr.com/mak4g7

**Comment by freudknows** [comment]
Space between notifications is quite big: http://prntscr.com/mak7gk

**Comment by freudknows** [comment]
http://prntscr.com/mak7zx 

Visual issue when product has been removed from cart.

**Comment by imfaisalkh** [comment]
Thanks for listing the issues out, I'll go through them each and will probably include them in next patch release.

**Comment by freudknows** [comment]
https://i.imgur.com/NwsmYyq.png

No visual css when a payment has been declined.

**Comment by freudknows** [comment]
Another issue: http://prntscr.com/mf7m3o

**Comment by freudknows** [comment]
Hey Faisal, will these issues also be included for version 1.5? :)

**Comment by imfaisalkh** [comment]
> Another issue: http://prntscr.com/mf7m3o

I've tried reproducing the issue, but I was unable to find any setting in woocommerce to disallow duplicate product order. Is it woocommerce default feature?

**Comment by imfaisalkh** [comment]
> https://i.imgur.com/NwsmYyq.png
> 
> No visual css when a payment has been declined.

Same as before, how can I reproduce this screen?

**Comment by imfaisalkh** [comment]
> http://prntscr.com/mak7zx
> 
> Visual issue when product has been removed from cart.

> Space between notifications is quite big: http://prntscr.com/mak7gk

> Issue #1: http://prntscr.com/majymh No visual support to create an account on checkout page.

> Issue #4: http://prntscr.com/mak3fh validation checks does not really fit visually in the theme. The colors green, red, pink and purple combined?

Fixed for next update.

> Issue #2: http://prntscr.com/mak07w placeholder 'password'?

How do you produce the "password" field here? because by default it is not available.

**Comment by imfaisalkh** [comment]
> Issue #3: http://prntscr.com/mak1c7 placeholder to choose bank is missing (it's different compared to the other placeholders)

It seems to be using somewhat different markup, are you using some plugin to add this payment methods?
