### ISSUE TITLE
Ability to disable the listing URL on sidebar 

### ISSUE THREAD

**Issue by freudknows** [imfaisalkh/capstone-issue-tracker#31]
It would be nice to disable the listing url on sidebar on job detail pages:
http://prntscr.com/ma24ks

**Comment by imfaisalkh** [comment]
For single job listing, this is already possible, (click the eye icon to toggle visibility):

![image](https://user-images.githubusercontent.com/10553273/51476599-cc8c4700-1da7-11e9-9ee0-30abb56bb0c3.png)

For single company and resume listing, this feature is included in v1.4.

**Comment by imfaisalkh** [comment]
Existing feature extended in v1.4.
