### ISSUE TITLE
Different color issues found on the theme

### ISSUE THREAD

**Issue by freudknows** [imfaisalkh/capstone-issue-tracker#32]
On this issue I will list all the color issues which has been found once a custom theme color has been set. 

1. 404 page error: http://prntscr.com/ma25pi 404 letters are orange
2. Coming...

**Comment by imfaisalkh** [comment]
Some of the color issues are addressed in v1.4 (in review process), including this one. Feel free to update the list if you find any other color issue.

**Comment by imfaisalkh** [comment]
V1.4 has fixed some custom color related issue, let me know if there is any other similiar issue.
