### ISSUE TITLE
Hard coded pages on dashboard page can be removed?

### ISSUE THREAD

**Issue by freudknows** [imfaisalkh/capstone-issue-tracker#38]
This area can be removed with the introduction of the custom menu functionality?

http://prntscr.com/mbkrs7

**Comment by imfaisalkh** [comment]
Yes, you can assign any page via wordpress menus to dashboard menu locations. The menu item can be any page with any label. Configuring, "Dashboard Pages" section in customizer is only required if you are using some pages which are optimized (styling-wise) for dashboard template AND you want to achieve some extra functionality, for example: plus icon against "Jobs", "Resumes" and "Alerts" page. We cannot display it against each link without identifying which "create new" page belongs to which master page.

![image](https://user-images.githubusercontent.com/10553273/51691903-8cce9500-201d-11e9-8b3d-6853141b7625.png)
