### ISSUE TITLE
Social sharing links not working

### ISSUE THREAD

**Issue by freudknows** [imfaisalkh/capstone-issue-tracker#40]
When social sharing links are disabled: http://prntscr.com/md52uy
They are still appearing on single job listings: http://prntscr.com/md5343

**Comment by imfaisalkh** [comment]
I'm unable to reproduce the issue on my installation, can you please make sure it is not browser cache issue?

**Comment by freudknows** [comment]
Server cache + website cache has been erased, tried multiple browsers (Chrome + FF)
Issue still exists (feel free to login on my website and check the issue by yourself 👍 )

**Comment by imfaisalkh** [comment]
It seems your site has a previous value stored for this option (from older capstonr-pro version), which was causing issue. I've just changed the value to something else and then reverted it back to 'disable' to force it to save new option values. It seems to fixed the issue.
