### ISSUE TITLE
Suggestion to 'block' WooCommerce pages

### ISSUE THREAD

**Issue by freudknows** [imfaisalkh/capstone-issue-tracker#43]
Faisal, 

I encountered a problem with WooCommerce. We've discussed this subject earlier. I second your idea to strip all the unneeded things (just like the my account page, which you already have stripped of the theme). 

But pages such as /shop /basket and product detail pages are still available and users will be able to see these pages by clicking on for example validation errors (basket URL). 

Would it be possible to completely strip these out of the theme? 

Thanks

**Comment by imfaisalkh** [comment]
For the `/shop/` page, cannot you overcome this issue by defining a custom shop page e.g in you case it could be pricing page, like this:

![image](https://user-images.githubusercontent.com/10553273/52347750-89d39b80-2a44-11e9-8896-4e335c174d1d.png)

**Comment by freudknows** [comment]
Unfortunately, that doesn't resolve the problem. Please check:

https://i.imgur.com/kFBLCra.png

**Comment by imfaisalkh** [comment]
Hmm, it seems woocommerce is manipulating the page query once it is marked as `shop` page. I'll see what would be the best approach to deal this issue.

**Comment by freudknows** [comment]
Thanks!

**Comment by imfaisalkh** [comment]
Fixed in theme v1.5
