### ISSUE TITLE
WP Job Manager Visibility (Myles)

### ISSUE THREAD

**Issue by imfaisalkh** [imfaisalkh/capstone-issue-tracker#6]
Please include "WP Job Manager Visibility" (by myles) integration. Restrict Content Pro is very limited. It only supports the ability to hide/show a complete listing. The visibility plugin of Myles is able to show/hide different custom fields, is able to create 'packages' to view, apply or browse the WP Job Manager pages.

This plugin can work with the WP Job Manager Packages, but it can work standalone as well. 

`Posting on behalf of customer`

**Comment by freudknows** [comment]
I am actually requesting two pages to be included for the WP Job Manager Visibility plugin. There are two pages on the frontend which requires more visual support for the theme. The first page is the dashboard page and will represent the amount of available credits. Users are able to purchase different visiblity packages and they are listed using a shortcode. They are listed as follows: 

Dashboard page: http://prntscr.com/man6qu

As you can see a list with available packages. And if a job detail listing has been seen, it will be added to the view list, as you can see here: http://prntscr.com/man7au

Non-registered users and visitors are able to browse my website freely, but certain custom fields are hidden from public. This is primary contact information. Once they create an account; they get a for example 5 'view credits' to see 5 job detail pages. When they enter a job detail listing page, they will be redirected to a different page with the following overview: 

http://prntscr.com/mana9j

It would be nice to have a little more styling on this page as well. On this page, the user can select which view package he would like to use. After selected, he will be redirected back to the job detail page.

**Comment by imfaisalkh** [comment]
@freudknows The pages you mentioned actually belongs to "WP Job Manager Packages" plugin instead, whose support is also scheduled for v1.5.

**Comment by imfaisalkh** [comment]
Plugin integration added in theme v1.5
